---
version: 2
updates:
  # Composer.
  - package-ecosystem: composer
    directory: "/"
    # Check daily at 5AM UTC.
    schedule:
      interval: daily
      time: "04:47"
    allow:
      - dependency-type: all
    open-pull-requests-limit: 15
    reviewers:
      - adamzimmermann
      - mmatsoo
    assignees:
      - mmatsoo
    versioning-strategy: auto
    labels:
      - "dependencies"
      - "dept: back-end :back:"
      - "php"
      - "site: platform-wide"
